<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CAVICSRGXFTVT2" name="CTD_Unprocessed_Events_Endpoint.Unprocessed_Events_Tombstone_Validation_cms_clients" tests="4" failures="4" timestamp="31 May 2019 21:07:51 GMT" time="7.405" errors="0">
  <testcase name="Test_for_validating_tomstone_event_sealedynchanges_cms_clients_existingclient" time="4.002" classname="CTD_Unprocessed_Events_Endpoint.Unprocessed_Events_Tombstone_Validation_cms_clients">
    <failure type="java.lang.AssertionError" message="An Event was triggered for the requested details expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: An Event was triggered for the requested details expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at CTD_Unprocessed_Events_Endpointresources.Unprocessed_Events_Endpoint_ValidationTest.exampleGetTest(Unprocessed_Events_Endpoint_ValidationTest.java:239)
at CTD_Unprocessed_Events_Endpoint.Unprocessed_Events_Tombstone_Validation_cms_clients.Test_for_validating_tomstone_event_sealedynchanges_cms_clients_existingclient(Unprocessed_Events_Tombstone_Validation_cms_clients.java:118)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test_for_validating_tomstone_event_sealedynchanges_cms_clients_existingclient -->
  <testcase name="Test_for_validating_tomstone_event_gendercdchanges_cms_clients_existingclient" time="1.098" classname="CTD_Unprocessed_Events_Endpoint.Unprocessed_Events_Tombstone_Validation_cms_clients">
    <failure type="java.lang.AssertionError" message="An Event was triggered for the requested details expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: An Event was triggered for the requested details expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at CTD_Unprocessed_Events_Endpointresources.Unprocessed_Events_Endpoint_ValidationTest.exampleGetTest(Unprocessed_Events_Endpoint_ValidationTest.java:239)
at CTD_Unprocessed_Events_Endpoint.Unprocessed_Events_Tombstone_Validation_cms_clients.Test_for_validating_tomstone_event_gendercdchanges_cms_clients_existingclient(Unprocessed_Events_Tombstone_Validation_cms_clients.java:274)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test_for_validating_tomstone_event_gendercdchanges_cms_clients_existingclient -->
  <testcase name="Test_for_validating_tomstone_event_gendercdchanges_cms_clients_existingclient" time="1.090" classname="CTD_Unprocessed_Events_Endpoint.Unprocessed_Events_Tombstone_Validation_cms_clients">
    <failure type="java.lang.AssertionError" message="no event triggered expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: no event triggered expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at CTD_Unprocessed_Events_Endpointresources.Unprocessed_Events_Endpoint_ValidationTest.exampleGetTest(Unprocessed_Events_Endpoint_ValidationTest.java:233)
at CTD_Unprocessed_Events_Endpoint.Unprocessed_Events_Tombstone_Validation_cms_clients.Test_for_validating_tomstone_event_gendercdchanges_cms_clients_existingclient(Unprocessed_Events_Tombstone_Validation_cms_clients.java:320)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test_for_validating_tomstone_event_gendercdchanges_cms_clients_existingclient -->
  <testcase name="Test_for_validating_tomstone_event_sealedynchanges_cms_clients_existingclient" time="1.215" classname="CTD_Unprocessed_Events_Endpoint.Unprocessed_Events_Tombstone_Validation_cms_clients">
    <failure type="java.lang.AssertionError" message="no event triggered expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: no event triggered expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at CTD_Unprocessed_Events_Endpointresources.Unprocessed_Events_Endpoint_ValidationTest.exampleGetTest(Unprocessed_Events_Endpoint_ValidationTest.java:233)
at CTD_Unprocessed_Events_Endpoint.Unprocessed_Events_Tombstone_Validation_cms_clients.Test_for_validating_tomstone_event_sealedynchanges_cms_clients_existingclient(Unprocessed_Events_Tombstone_Validation_cms_clients.java:161)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test_for_validating_tomstone_event_sealedynchanges_cms_clients_existingclient -->
</testsuite> <!-- CTD_Unprocessed_Events_Endpoint.Unprocessed_Events_Tombstone_Validation_cms_clients -->
